### ISSUE TITLE
Code availability

### ISSUE THREAD

**Issue by aras62** [MoonBlvd/fvl-ICRA2019#1]
The code folders for keras implementation are still empty. Are you planning to release the code at some point?

**Comment by MoonBlvd** [comment]
Hi @aras62  thank you for your interest! We published our pytorch code here: https://github.com/MoonBlvd/tad-IROS2019
This is a different paper but the FOL codes are similar and the evaluation results on HEV-I dataset is also presented in that repo. Unfortunately we are not going to publish Keras code anymore.

**Comment by aras62** [comment]
Thanks for your prompt response
